language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: fCLR2jWrikGjFY081vznqy7/wecWPnkEEpQEtuw+kSzyMO31Av43U3MXCKjH4enQ8UL2LGh8VbiSBSTck+2PGNA8KZKLNUbXgKk0L/K2lSYrpL3G6iXC4s1FcSHsMAXvQhSkmR4/hWNqAaUc0yUGoZdqAOaZIw3Li14R/WtKsO8=
  - secure: hQdb4WNIpI+Bet34JmQBVE5dXWOWU1bn1JaQI1/ypuRkAVfKJercEs9/pl2e7bx0B7iU9qREMqsddFLNOXtbWEszUdujQ/hzR3EP+uBttTS9lOkAxLa9OqHzdngZCNoFGBSojwPUqtZgxBioJd4/kzZGrpLh9kLbvrEXIUuXYD8=
